theme: jekyll-theme-dinky
title: Sanat Gogoi
description: Assistant Professor, Department of Physics, Digboi College, Digboi-786171 Assam
avatar: https://github.com/sanatgogoi/digboi_college_physics_sanat_profile/blob/main/doc/IMG_20181216_151920.jpg
